# Setup and configure Nginx
- name: "Nginx: setting up"
  hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo

  tasks:
  - name: Install Nginx
    apt: "name={{ item }} state=present"
    with_items:
      - nginx
      - nginx-extras

# debug:
#   msg: "some message"